name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set LIFF_ID and GAS_URL environment variables
        run: |
          echo "LIFF_ID_HIGHBRAND=${{ secrets.LIFF_ID_HIGHBRAND }}" >> $GITHUB_ENV
          echo "GAS_URL=${{ secrets.GAS_URL }}" >> $GITHUB_ENV

      - name: Generate config.js
        run: |
          if [ -z "${{ env.LIFF_ID_HIGHBRAND }}" ]; then
            echo "Error: LIFF_ID_HIGHBRAND environment variable is not set."
            exit 1
          fi
          if [ -z "${{ env.GAS_URL }}" ]; then
            echo "Error: GAS_URL environment variable is not set."
            exit 1
          fi
          echo "const config = { liffId_HighBrand: '${{ env.LIFF_ID_HIGHBRAND }}', gasUrl: '${{ env.GAS_URL }}' };" > config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
